// <auto-generated />
using System;
using GestionUnivApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionUnivApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331042513_InitialModel")]
    partial class InitialModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionUnivApp.Models.ChoixSpecialisation", b =>
                {
                    b.Property<int>("Id_ChoixSpec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ChoixSpec"));

                    b.Property<DateTime>("DateChoixSpec")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Spec")
                        .HasColumnType("int");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<int>("Nb_ChoixSpec")
                        .HasColumnType("int");

                    b.HasKey("Id_ChoixSpec");

                    b.HasIndex("Id_Spec");

                    b.HasIndex("Id_User");

                    b.ToTable("ChoixSpecialisations");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Cours", b =>
                {
                    b.Property<int>("Id_Cours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cours"));

                    b.Property<string>("Code_Cours")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Credit_Cours")
                        .HasColumnType("int");

                    b.Property<int?>("NbHeure_Cours")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Cours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_Cours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Cours");

                    b.HasIndex("Code_Cours")
                        .IsUnique();

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("GestionUnivApp.Models.CoursOffert", b =>
                {
                    b.Property<int>("Id_CoursOf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CoursOf"));

                    b.Property<int>("Capacite_CoursOf")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateDeb_CoursOf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin_CoursOf")
                        .HasColumnType("datetime2");

                    b.Property<string>("Horaire_CoursOf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Cours")
                        .HasColumnType("int");

                    b.Property<string>("MondeEns_CoursOf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salle_CoursOf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sect_CoursOf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_CoursOf");

                    b.HasIndex("Id_Cours");

                    b.ToTable("CoursOfferts");
                });

            modelBuilder.Entity("GestionUnivApp.Models.CoursPrerequis", b =>
                {
                    b.Property<int>("Id_Prerequis")
                        .HasColumnType("int");

                    b.Property<int>("Id_Cours")
                        .HasColumnType("int");

                    b.Property<int>("IdèCoursPre")
                        .HasColumnType("int");

                    b.HasKey("Id_Prerequis");

                    b.HasIndex("Id_Cours");

                    b.ToTable("CoursPrerequis");
                });

            modelBuilder.Entity("GestionUnivApp.Models.CoursProgramme", b =>
                {
                    b.Property<int>("Id_CoursProg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CoursProg"));

                    b.Property<int>("Id_Cours")
                        .HasColumnType("int");

                    b.Property<int>("Id_Prog")
                        .HasColumnType("int");

                    b.HasKey("Id_CoursProg");

                    b.HasIndex("Id_Cours");

                    b.HasIndex("Id_Prog");

                    b.ToTable("CoursProgrammes");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Enseigner", b =>
                {
                    b.Property<int>("Id_Enseigner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Enseigner"));

                    b.Property<DateTime?>("DateDeb_Enseigner")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin_Enseigner")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_CoursOf")
                        .HasColumnType("int");

                    b.Property<int>("Id_Prof")
                        .HasColumnType("int");

                    b.Property<int>("NbH_Enseigner")
                        .HasColumnType("int");

                    b.HasKey("Id_Enseigner");

                    b.HasIndex("Id_CoursOf");

                    b.HasIndex("Id_Prof");

                    b.ToTable("Enseignements");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Evaluation", b =>
                {
                    b.Property<int>("Id_Eval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Eval"));

                    b.Property<DateTime>("Date_Eval")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descript_Eval")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_CoursOf")
                        .HasColumnType("int");

                    b.Property<int>("Id_SessExam")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Eval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Poids_Eval")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type_Eval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Eval");

                    b.HasIndex("Id_CoursOf");

                    b.HasIndex("Id_SessExam");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Inscription", b =>
                {
                    b.Property<int>("Id_Inscript")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Inscript"));

                    b.Property<DateTime?>("Date_Desinscript")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Inscript")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionFi_Inscript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_CoursOf")
                        .HasColumnType("int");

                    b.Property<int>("Id_Etud")
                        .HasColumnType("int");

                    b.Property<decimal?>("NoteFi_Inscript")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoteLet_Inscript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut_Inscript")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Inscript");

                    b.HasIndex("Id_CoursOf");

                    b.HasIndex("Id_Etud", "Id_CoursOf")
                        .IsUnique();

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Note", b =>
                {
                    b.Property<int>("Id_Note")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Note"));

                    b.Property<DateTime?>("DateAttrib_Note")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Eval")
                        .HasColumnType("int");

                    b.Property<int>("Id_Inscript")
                        .HasColumnType("int");

                    b.Property<string>("RetroAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValLet_Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValNum_Note")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Note");

                    b.HasIndex("Id_Eval");

                    b.HasIndex("Id_Inscript");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Programme", b =>
                {
                    b.Property<int>("Id_Prog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Prog"));

                    b.Property<DateTime?>("DateCreat_Prog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description_Prog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duree_Prog")
                        .HasColumnType("int");

                    b.Property<int>("NbCredit_Prog")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Prog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unite_Prog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_Prog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Prog");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Restreindre", b =>
                {
                    b.Property<int>("Id_Rest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Rest"));

                    b.Property<int>("Id_Cours")
                        .HasColumnType("int");

                    b.Property<int>("Id_Spec")
                        .HasColumnType("int");

                    b.Property<int?>("Nb_Restrict")
                        .HasColumnType("int");

                    b.HasKey("Id_Rest");

                    b.HasIndex("Id_Cours");

                    b.HasIndex("Id_Spec");

                    b.ToTable("Restrictions");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Semestre", b =>
                {
                    b.Property<int>("Id_Semest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Semest"));

                    b.Property<string>("Annee_Semest")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateDeb_Semest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin_Semest")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom_Semest")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_Semest");

                    b.HasIndex("Nom_Semest", "Annee_Semest")
                        .IsUnique();

                    b.ToTable("Semestres");
                });

            modelBuilder.Entity("GestionUnivApp.Models.SessionExamen", b =>
                {
                    b.Property<int>("Id_SessExam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_SessExam"));

                    b.Property<DateTime>("DateDeb")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Semest")
                        .HasColumnType("int");

                    b.Property<string>("Type_SessExam")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_SessExam");

                    b.HasIndex("Id_Semest");

                    b.HasIndex("Type_SessExam", "DateDeb")
                        .IsUnique();

                    b.ToTable("SessionsExamen");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Specialisation", b =>
                {
                    b.Property<int>("Id_Spec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Spec"));

                    b.Property<string>("Description_Spec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Prog_Spec")
                        .HasColumnType("int");

                    b.Property<int>("NbCredit_Spec")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Spec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Spec");

                    b.HasIndex("Id_Prog_Spec");

                    b.ToTable("Specialisations");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_User");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adresse_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Courriel_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateInscriptUser")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissUser")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mat_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Num_Tel_User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Mat_User")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Utilisateur", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GestionUnivApp.Models.Administrateur", b =>
                {
                    b.HasBaseType("GestionUnivApp.Models.Utilisateur");

                    b.Property<string>("Role_Admin_Etud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Administrateur", (string)null);
                });

            modelBuilder.Entity("GestionUnivApp.Models.Etudiant", b =>
                {
                    b.HasBaseType("GestionUnivApp.Models.Utilisateur");

                    b.Property<int>("Programme_Etud")
                        .HasColumnType("int");

                    b.Property<string>("Statut_Etudiant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Programme_Etud");

                    b.ToTable("Etudiant", (string)null);
                });

            modelBuilder.Entity("GestionUnivApp.Models.Professeur", b =>
                {
                    b.HasBaseType("GestionUnivApp.Models.Utilisateur");

                    b.Property<string>("Grade_Prof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut_Prof")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Professeur", (string)null);
                });

            modelBuilder.Entity("GestionUnivApp.Models.ChoixSpecialisation", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Specialisation", "Specialisation")
                        .WithMany("ChoixSpecialisations")
                        .HasForeignKey("Id_Spec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Etudiant", "Etudiant")
                        .WithMany("ChoixSpecialisations")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Specialisation");
                });

            modelBuilder.Entity("GestionUnivApp.Models.CoursOffert", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Cours", "Cours")
                        .WithMany("CoursOfferts")
                        .HasForeignKey("Id_Cours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");
                });

            modelBuilder.Entity("GestionUnivApp.Models.CoursPrerequis", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Cours", "Cours")
                        .WithMany("Prerequis")
                        .HasForeignKey("Id_Cours")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Cours", "Prerequis")
                        .WithMany("EstPrerequisDe")
                        .HasForeignKey("Id_Prerequis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Prerequis");
                });

            modelBuilder.Entity("GestionUnivApp.Models.CoursProgramme", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Cours", "Cours")
                        .WithMany("CoursProgrammes")
                        .HasForeignKey("Id_Cours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Programme", "Programme")
                        .WithMany("CoursProgrammes")
                        .HasForeignKey("Id_Prog")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Enseigner", b =>
                {
                    b.HasOne("GestionUnivApp.Models.CoursOffert", "CoursOffert")
                        .WithMany("Enseignements")
                        .HasForeignKey("Id_CoursOf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Professeur", "Professeur")
                        .WithMany("Enseignements")
                        .HasForeignKey("Id_Prof")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursOffert");

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Evaluation", b =>
                {
                    b.HasOne("GestionUnivApp.Models.CoursOffert", "CoursOffert")
                        .WithMany("Evaluations")
                        .HasForeignKey("Id_CoursOf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.SessionExamen", "SessionExamen")
                        .WithMany("Evaluations")
                        .HasForeignKey("Id_SessExam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursOffert");

                    b.Navigation("SessionExamen");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Inscription", b =>
                {
                    b.HasOne("GestionUnivApp.Models.CoursOffert", "CoursOffert")
                        .WithMany("Inscriptions")
                        .HasForeignKey("Id_CoursOf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Etudiant", "Etudiant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("Id_Etud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoursOffert");

                    b.Navigation("Etudiant");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Note", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Evaluation", "Evaluation")
                        .WithMany("Notes")
                        .HasForeignKey("Id_Eval")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Inscription", "Inscription")
                        .WithMany("Notes")
                        .HasForeignKey("Id_Inscript")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Inscription");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Restreindre", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Cours", "Cours")
                        .WithMany("Restrictions")
                        .HasForeignKey("Id_Cours")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Specialisation", "Specialisation")
                        .WithMany("Restrictions")
                        .HasForeignKey("Id_Spec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Specialisation");
                });

            modelBuilder.Entity("GestionUnivApp.Models.SessionExamen", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Semestre", "Semestre")
                        .WithMany("SessionExamens")
                        .HasForeignKey("Id_Semest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semestre");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Specialisation", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Programme", "Programme")
                        .WithMany("Specialisations")
                        .HasForeignKey("Id_Prog_Spec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionUnivApp.Models.Administrateur", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("GestionUnivApp.Models.Administrateur", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionUnivApp.Models.Etudiant", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("GestionUnivApp.Models.Etudiant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionUnivApp.Models.Programme", "Programme")
                        .WithMany("Etudiants")
                        .HasForeignKey("Programme_Etud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Professeur", b =>
                {
                    b.HasOne("GestionUnivApp.Models.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("GestionUnivApp.Models.Professeur", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionUnivApp.Models.Cours", b =>
                {
                    b.Navigation("CoursOfferts");

                    b.Navigation("CoursProgrammes");

                    b.Navigation("EstPrerequisDe");

                    b.Navigation("Prerequis");

                    b.Navigation("Restrictions");
                });

            modelBuilder.Entity("GestionUnivApp.Models.CoursOffert", b =>
                {
                    b.Navigation("Enseignements");

                    b.Navigation("Evaluations");

                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Evaluation", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Inscription", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Programme", b =>
                {
                    b.Navigation("CoursProgrammes");

                    b.Navigation("Etudiants");

                    b.Navigation("Specialisations");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Semestre", b =>
                {
                    b.Navigation("SessionExamens");
                });

            modelBuilder.Entity("GestionUnivApp.Models.SessionExamen", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Specialisation", b =>
                {
                    b.Navigation("ChoixSpecialisations");

                    b.Navigation("Restrictions");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Etudiant", b =>
                {
                    b.Navigation("ChoixSpecialisations");

                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("GestionUnivApp.Models.Professeur", b =>
                {
                    b.Navigation("Enseignements");
                });
#pragma warning restore 612, 618
        }
    }
}
